/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ch.scigility.kafka.canonical.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ContractsSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1707344960876421271L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ContractsSchema\",\"namespace\":\"ch.scigility.kafka.canonical.avro\",\"fields\":[{\"name\":\"INCO_ID\",\"type\":\"long\"},{\"name\":\"INCO_TYPE\",\"type\":\"long\"},{\"name\":\"INCO_COVERAGE\",\"type\":\"long\"},{\"name\":\"INCO_ANNUAL_PREMIUM\",\"type\":\"long\"},{\"name\":\"INCO_START_DATE\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"INCO_END_DATE\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"INCO_INPA_CUST_ID\",\"type\":\"long\"},{\"name\":\"INCO_INAG_ID\",\"type\":\"long\"},{\"name\":\"INCO_RENTABILITY\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ContractsSchema> ENCODER =
      new BinaryMessageEncoder<ContractsSchema>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ContractsSchema> DECODER =
      new BinaryMessageDecoder<ContractsSchema>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ContractsSchema> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ContractsSchema> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ContractsSchema>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ContractsSchema to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ContractsSchema from a ByteBuffer. */
  public static ContractsSchema fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long INCO_ID;
  @Deprecated public long INCO_TYPE;
  @Deprecated public long INCO_COVERAGE;
  @Deprecated public long INCO_ANNUAL_PREMIUM;
  @Deprecated public org.joda.time.DateTime INCO_START_DATE;
  @Deprecated public org.joda.time.DateTime INCO_END_DATE;
  @Deprecated public long INCO_INPA_CUST_ID;
  @Deprecated public long INCO_INAG_ID;
  @Deprecated public long INCO_RENTABILITY;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ContractsSchema() {}

  /**
   * All-args constructor.
   * @param INCO_ID The new value for INCO_ID
   * @param INCO_TYPE The new value for INCO_TYPE
   * @param INCO_COVERAGE The new value for INCO_COVERAGE
   * @param INCO_ANNUAL_PREMIUM The new value for INCO_ANNUAL_PREMIUM
   * @param INCO_START_DATE The new value for INCO_START_DATE
   * @param INCO_END_DATE The new value for INCO_END_DATE
   * @param INCO_INPA_CUST_ID The new value for INCO_INPA_CUST_ID
   * @param INCO_INAG_ID The new value for INCO_INAG_ID
   * @param INCO_RENTABILITY The new value for INCO_RENTABILITY
   */
  public ContractsSchema(java.lang.Long INCO_ID, java.lang.Long INCO_TYPE, java.lang.Long INCO_COVERAGE, java.lang.Long INCO_ANNUAL_PREMIUM, org.joda.time.DateTime INCO_START_DATE, org.joda.time.DateTime INCO_END_DATE, java.lang.Long INCO_INPA_CUST_ID, java.lang.Long INCO_INAG_ID, java.lang.Long INCO_RENTABILITY) {
    this.INCO_ID = INCO_ID;
    this.INCO_TYPE = INCO_TYPE;
    this.INCO_COVERAGE = INCO_COVERAGE;
    this.INCO_ANNUAL_PREMIUM = INCO_ANNUAL_PREMIUM;
    this.INCO_START_DATE = INCO_START_DATE;
    this.INCO_END_DATE = INCO_END_DATE;
    this.INCO_INPA_CUST_ID = INCO_INPA_CUST_ID;
    this.INCO_INAG_ID = INCO_INAG_ID;
    this.INCO_RENTABILITY = INCO_RENTABILITY;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return INCO_ID;
    case 1: return INCO_TYPE;
    case 2: return INCO_COVERAGE;
    case 3: return INCO_ANNUAL_PREMIUM;
    case 4: return INCO_START_DATE;
    case 5: return INCO_END_DATE;
    case 6: return INCO_INPA_CUST_ID;
    case 7: return INCO_INAG_ID;
    case 8: return INCO_RENTABILITY;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  protected static final org.apache.avro.data.TimeConversions.DateConversion DATE_CONVERSION = new org.apache.avro.data.TimeConversions.DateConversion();
  protected static final org.apache.avro.data.TimeConversions.TimeConversion TIME_CONVERSION = new org.apache.avro.data.TimeConversions.TimeConversion();
  protected static final org.apache.avro.data.TimeConversions.TimestampConversion TIMESTAMP_CONVERSION = new org.apache.avro.data.TimeConversions.TimestampConversion();
  protected static final org.apache.avro.Conversions.DecimalConversion DECIMAL_CONVERSION = new org.apache.avro.Conversions.DecimalConversion();

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      TIMESTAMP_CONVERSION,
      TIMESTAMP_CONVERSION,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: INCO_ID = (java.lang.Long)value$; break;
    case 1: INCO_TYPE = (java.lang.Long)value$; break;
    case 2: INCO_COVERAGE = (java.lang.Long)value$; break;
    case 3: INCO_ANNUAL_PREMIUM = (java.lang.Long)value$; break;
    case 4: INCO_START_DATE = (org.joda.time.DateTime)value$; break;
    case 5: INCO_END_DATE = (org.joda.time.DateTime)value$; break;
    case 6: INCO_INPA_CUST_ID = (java.lang.Long)value$; break;
    case 7: INCO_INAG_ID = (java.lang.Long)value$; break;
    case 8: INCO_RENTABILITY = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'INCO_ID' field.
   * @return The value of the 'INCO_ID' field.
   */
  public java.lang.Long getINCOID() {
    return INCO_ID;
  }

  /**
   * Sets the value of the 'INCO_ID' field.
   * @param value the value to set.
   */
  public void setINCOID(java.lang.Long value) {
    this.INCO_ID = value;
  }

  /**
   * Gets the value of the 'INCO_TYPE' field.
   * @return The value of the 'INCO_TYPE' field.
   */
  public java.lang.Long getINCOTYPE() {
    return INCO_TYPE;
  }

  /**
   * Sets the value of the 'INCO_TYPE' field.
   * @param value the value to set.
   */
  public void setINCOTYPE(java.lang.Long value) {
    this.INCO_TYPE = value;
  }

  /**
   * Gets the value of the 'INCO_COVERAGE' field.
   * @return The value of the 'INCO_COVERAGE' field.
   */
  public java.lang.Long getINCOCOVERAGE() {
    return INCO_COVERAGE;
  }

  /**
   * Sets the value of the 'INCO_COVERAGE' field.
   * @param value the value to set.
   */
  public void setINCOCOVERAGE(java.lang.Long value) {
    this.INCO_COVERAGE = value;
  }

  /**
   * Gets the value of the 'INCO_ANNUAL_PREMIUM' field.
   * @return The value of the 'INCO_ANNUAL_PREMIUM' field.
   */
  public java.lang.Long getINCOANNUALPREMIUM() {
    return INCO_ANNUAL_PREMIUM;
  }

  /**
   * Sets the value of the 'INCO_ANNUAL_PREMIUM' field.
   * @param value the value to set.
   */
  public void setINCOANNUALPREMIUM(java.lang.Long value) {
    this.INCO_ANNUAL_PREMIUM = value;
  }

  /**
   * Gets the value of the 'INCO_START_DATE' field.
   * @return The value of the 'INCO_START_DATE' field.
   */
  public org.joda.time.DateTime getINCOSTARTDATE() {
    return INCO_START_DATE;
  }

  /**
   * Sets the value of the 'INCO_START_DATE' field.
   * @param value the value to set.
   */
  public void setINCOSTARTDATE(org.joda.time.DateTime value) {
    this.INCO_START_DATE = value;
  }

  /**
   * Gets the value of the 'INCO_END_DATE' field.
   * @return The value of the 'INCO_END_DATE' field.
   */
  public org.joda.time.DateTime getINCOENDDATE() {
    return INCO_END_DATE;
  }

  /**
   * Sets the value of the 'INCO_END_DATE' field.
   * @param value the value to set.
   */
  public void setINCOENDDATE(org.joda.time.DateTime value) {
    this.INCO_END_DATE = value;
  }

  /**
   * Gets the value of the 'INCO_INPA_CUST_ID' field.
   * @return The value of the 'INCO_INPA_CUST_ID' field.
   */
  public java.lang.Long getINCOINPACUSTID() {
    return INCO_INPA_CUST_ID;
  }

  /**
   * Sets the value of the 'INCO_INPA_CUST_ID' field.
   * @param value the value to set.
   */
  public void setINCOINPACUSTID(java.lang.Long value) {
    this.INCO_INPA_CUST_ID = value;
  }

  /**
   * Gets the value of the 'INCO_INAG_ID' field.
   * @return The value of the 'INCO_INAG_ID' field.
   */
  public java.lang.Long getINCOINAGID() {
    return INCO_INAG_ID;
  }

  /**
   * Sets the value of the 'INCO_INAG_ID' field.
   * @param value the value to set.
   */
  public void setINCOINAGID(java.lang.Long value) {
    this.INCO_INAG_ID = value;
  }

  /**
   * Gets the value of the 'INCO_RENTABILITY' field.
   * @return The value of the 'INCO_RENTABILITY' field.
   */
  public java.lang.Long getINCORENTABILITY() {
    return INCO_RENTABILITY;
  }

  /**
   * Sets the value of the 'INCO_RENTABILITY' field.
   * @param value the value to set.
   */
  public void setINCORENTABILITY(java.lang.Long value) {
    this.INCO_RENTABILITY = value;
  }

  /**
   * Creates a new ContractsSchema RecordBuilder.
   * @return A new ContractsSchema RecordBuilder
   */
  public static ch.scigility.kafka.canonical.avro.ContractsSchema.Builder newBuilder() {
    return new ch.scigility.kafka.canonical.avro.ContractsSchema.Builder();
  }

  /**
   * Creates a new ContractsSchema RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ContractsSchema RecordBuilder
   */
  public static ch.scigility.kafka.canonical.avro.ContractsSchema.Builder newBuilder(ch.scigility.kafka.canonical.avro.ContractsSchema.Builder other) {
    return new ch.scigility.kafka.canonical.avro.ContractsSchema.Builder(other);
  }

  /**
   * Creates a new ContractsSchema RecordBuilder by copying an existing ContractsSchema instance.
   * @param other The existing instance to copy.
   * @return A new ContractsSchema RecordBuilder
   */
  public static ch.scigility.kafka.canonical.avro.ContractsSchema.Builder newBuilder(ch.scigility.kafka.canonical.avro.ContractsSchema other) {
    return new ch.scigility.kafka.canonical.avro.ContractsSchema.Builder(other);
  }

  /**
   * RecordBuilder for ContractsSchema instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ContractsSchema>
    implements org.apache.avro.data.RecordBuilder<ContractsSchema> {

    private long INCO_ID;
    private long INCO_TYPE;
    private long INCO_COVERAGE;
    private long INCO_ANNUAL_PREMIUM;
    private org.joda.time.DateTime INCO_START_DATE;
    private org.joda.time.DateTime INCO_END_DATE;
    private long INCO_INPA_CUST_ID;
    private long INCO_INAG_ID;
    private long INCO_RENTABILITY;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ch.scigility.kafka.canonical.avro.ContractsSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.INCO_ID)) {
        this.INCO_ID = data().deepCopy(fields()[0].schema(), other.INCO_ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.INCO_TYPE)) {
        this.INCO_TYPE = data().deepCopy(fields()[1].schema(), other.INCO_TYPE);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.INCO_COVERAGE)) {
        this.INCO_COVERAGE = data().deepCopy(fields()[2].schema(), other.INCO_COVERAGE);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.INCO_ANNUAL_PREMIUM)) {
        this.INCO_ANNUAL_PREMIUM = data().deepCopy(fields()[3].schema(), other.INCO_ANNUAL_PREMIUM);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.INCO_START_DATE)) {
        this.INCO_START_DATE = data().deepCopy(fields()[4].schema(), other.INCO_START_DATE);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.INCO_END_DATE)) {
        this.INCO_END_DATE = data().deepCopy(fields()[5].schema(), other.INCO_END_DATE);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.INCO_INPA_CUST_ID)) {
        this.INCO_INPA_CUST_ID = data().deepCopy(fields()[6].schema(), other.INCO_INPA_CUST_ID);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.INCO_INAG_ID)) {
        this.INCO_INAG_ID = data().deepCopy(fields()[7].schema(), other.INCO_INAG_ID);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.INCO_RENTABILITY)) {
        this.INCO_RENTABILITY = data().deepCopy(fields()[8].schema(), other.INCO_RENTABILITY);
        fieldSetFlags()[8] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ContractsSchema instance
     * @param other The existing instance to copy.
     */
    private Builder(ch.scigility.kafka.canonical.avro.ContractsSchema other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.INCO_ID)) {
        this.INCO_ID = data().deepCopy(fields()[0].schema(), other.INCO_ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.INCO_TYPE)) {
        this.INCO_TYPE = data().deepCopy(fields()[1].schema(), other.INCO_TYPE);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.INCO_COVERAGE)) {
        this.INCO_COVERAGE = data().deepCopy(fields()[2].schema(), other.INCO_COVERAGE);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.INCO_ANNUAL_PREMIUM)) {
        this.INCO_ANNUAL_PREMIUM = data().deepCopy(fields()[3].schema(), other.INCO_ANNUAL_PREMIUM);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.INCO_START_DATE)) {
        this.INCO_START_DATE = data().deepCopy(fields()[4].schema(), other.INCO_START_DATE);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.INCO_END_DATE)) {
        this.INCO_END_DATE = data().deepCopy(fields()[5].schema(), other.INCO_END_DATE);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.INCO_INPA_CUST_ID)) {
        this.INCO_INPA_CUST_ID = data().deepCopy(fields()[6].schema(), other.INCO_INPA_CUST_ID);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.INCO_INAG_ID)) {
        this.INCO_INAG_ID = data().deepCopy(fields()[7].schema(), other.INCO_INAG_ID);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.INCO_RENTABILITY)) {
        this.INCO_RENTABILITY = data().deepCopy(fields()[8].schema(), other.INCO_RENTABILITY);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'INCO_ID' field.
      * @return The value.
      */
    public java.lang.Long getINCOID() {
      return INCO_ID;
    }

    /**
      * Sets the value of the 'INCO_ID' field.
      * @param value The value of 'INCO_ID'.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder setINCOID(long value) {
      validate(fields()[0], value);
      this.INCO_ID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'INCO_ID' field has been set.
      * @return True if the 'INCO_ID' field has been set, false otherwise.
      */
    public boolean hasINCOID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'INCO_ID' field.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder clearINCOID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'INCO_TYPE' field.
      * @return The value.
      */
    public java.lang.Long getINCOTYPE() {
      return INCO_TYPE;
    }

    /**
      * Sets the value of the 'INCO_TYPE' field.
      * @param value The value of 'INCO_TYPE'.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder setINCOTYPE(long value) {
      validate(fields()[1], value);
      this.INCO_TYPE = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'INCO_TYPE' field has been set.
      * @return True if the 'INCO_TYPE' field has been set, false otherwise.
      */
    public boolean hasINCOTYPE() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'INCO_TYPE' field.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder clearINCOTYPE() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'INCO_COVERAGE' field.
      * @return The value.
      */
    public java.lang.Long getINCOCOVERAGE() {
      return INCO_COVERAGE;
    }

    /**
      * Sets the value of the 'INCO_COVERAGE' field.
      * @param value The value of 'INCO_COVERAGE'.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder setINCOCOVERAGE(long value) {
      validate(fields()[2], value);
      this.INCO_COVERAGE = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'INCO_COVERAGE' field has been set.
      * @return True if the 'INCO_COVERAGE' field has been set, false otherwise.
      */
    public boolean hasINCOCOVERAGE() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'INCO_COVERAGE' field.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder clearINCOCOVERAGE() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'INCO_ANNUAL_PREMIUM' field.
      * @return The value.
      */
    public java.lang.Long getINCOANNUALPREMIUM() {
      return INCO_ANNUAL_PREMIUM;
    }

    /**
      * Sets the value of the 'INCO_ANNUAL_PREMIUM' field.
      * @param value The value of 'INCO_ANNUAL_PREMIUM'.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder setINCOANNUALPREMIUM(long value) {
      validate(fields()[3], value);
      this.INCO_ANNUAL_PREMIUM = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'INCO_ANNUAL_PREMIUM' field has been set.
      * @return True if the 'INCO_ANNUAL_PREMIUM' field has been set, false otherwise.
      */
    public boolean hasINCOANNUALPREMIUM() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'INCO_ANNUAL_PREMIUM' field.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder clearINCOANNUALPREMIUM() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'INCO_START_DATE' field.
      * @return The value.
      */
    public org.joda.time.DateTime getINCOSTARTDATE() {
      return INCO_START_DATE;
    }

    /**
      * Sets the value of the 'INCO_START_DATE' field.
      * @param value The value of 'INCO_START_DATE'.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder setINCOSTARTDATE(org.joda.time.DateTime value) {
      validate(fields()[4], value);
      this.INCO_START_DATE = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'INCO_START_DATE' field has been set.
      * @return True if the 'INCO_START_DATE' field has been set, false otherwise.
      */
    public boolean hasINCOSTARTDATE() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'INCO_START_DATE' field.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder clearINCOSTARTDATE() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'INCO_END_DATE' field.
      * @return The value.
      */
    public org.joda.time.DateTime getINCOENDDATE() {
      return INCO_END_DATE;
    }

    /**
      * Sets the value of the 'INCO_END_DATE' field.
      * @param value The value of 'INCO_END_DATE'.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder setINCOENDDATE(org.joda.time.DateTime value) {
      validate(fields()[5], value);
      this.INCO_END_DATE = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'INCO_END_DATE' field has been set.
      * @return True if the 'INCO_END_DATE' field has been set, false otherwise.
      */
    public boolean hasINCOENDDATE() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'INCO_END_DATE' field.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder clearINCOENDDATE() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'INCO_INPA_CUST_ID' field.
      * @return The value.
      */
    public java.lang.Long getINCOINPACUSTID() {
      return INCO_INPA_CUST_ID;
    }

    /**
      * Sets the value of the 'INCO_INPA_CUST_ID' field.
      * @param value The value of 'INCO_INPA_CUST_ID'.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder setINCOINPACUSTID(long value) {
      validate(fields()[6], value);
      this.INCO_INPA_CUST_ID = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'INCO_INPA_CUST_ID' field has been set.
      * @return True if the 'INCO_INPA_CUST_ID' field has been set, false otherwise.
      */
    public boolean hasINCOINPACUSTID() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'INCO_INPA_CUST_ID' field.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder clearINCOINPACUSTID() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'INCO_INAG_ID' field.
      * @return The value.
      */
    public java.lang.Long getINCOINAGID() {
      return INCO_INAG_ID;
    }

    /**
      * Sets the value of the 'INCO_INAG_ID' field.
      * @param value The value of 'INCO_INAG_ID'.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder setINCOINAGID(long value) {
      validate(fields()[7], value);
      this.INCO_INAG_ID = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'INCO_INAG_ID' field has been set.
      * @return True if the 'INCO_INAG_ID' field has been set, false otherwise.
      */
    public boolean hasINCOINAGID() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'INCO_INAG_ID' field.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder clearINCOINAGID() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'INCO_RENTABILITY' field.
      * @return The value.
      */
    public java.lang.Long getINCORENTABILITY() {
      return INCO_RENTABILITY;
    }

    /**
      * Sets the value of the 'INCO_RENTABILITY' field.
      * @param value The value of 'INCO_RENTABILITY'.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder setINCORENTABILITY(long value) {
      validate(fields()[8], value);
      this.INCO_RENTABILITY = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'INCO_RENTABILITY' field has been set.
      * @return True if the 'INCO_RENTABILITY' field has been set, false otherwise.
      */
    public boolean hasINCORENTABILITY() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'INCO_RENTABILITY' field.
      * @return This builder.
      */
    public ch.scigility.kafka.canonical.avro.ContractsSchema.Builder clearINCORENTABILITY() {
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ContractsSchema build() {
      try {
        ContractsSchema record = new ContractsSchema();
        record.INCO_ID = fieldSetFlags()[0] ? this.INCO_ID : (java.lang.Long) defaultValue(fields()[0], record.getConversion(0));
        record.INCO_TYPE = fieldSetFlags()[1] ? this.INCO_TYPE : (java.lang.Long) defaultValue(fields()[1], record.getConversion(1));
        record.INCO_COVERAGE = fieldSetFlags()[2] ? this.INCO_COVERAGE : (java.lang.Long) defaultValue(fields()[2], record.getConversion(2));
        record.INCO_ANNUAL_PREMIUM = fieldSetFlags()[3] ? this.INCO_ANNUAL_PREMIUM : (java.lang.Long) defaultValue(fields()[3], record.getConversion(3));
        record.INCO_START_DATE = fieldSetFlags()[4] ? this.INCO_START_DATE : (org.joda.time.DateTime) defaultValue(fields()[4], record.getConversion(4));
        record.INCO_END_DATE = fieldSetFlags()[5] ? this.INCO_END_DATE : (org.joda.time.DateTime) defaultValue(fields()[5], record.getConversion(5));
        record.INCO_INPA_CUST_ID = fieldSetFlags()[6] ? this.INCO_INPA_CUST_ID : (java.lang.Long) defaultValue(fields()[6], record.getConversion(6));
        record.INCO_INAG_ID = fieldSetFlags()[7] ? this.INCO_INAG_ID : (java.lang.Long) defaultValue(fields()[7], record.getConversion(7));
        record.INCO_RENTABILITY = fieldSetFlags()[8] ? this.INCO_RENTABILITY : (java.lang.Long) defaultValue(fields()[8], record.getConversion(8));
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ContractsSchema>
    WRITER$ = (org.apache.avro.io.DatumWriter<ContractsSchema>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ContractsSchema>
    READER$ = (org.apache.avro.io.DatumReader<ContractsSchema>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
